In [27]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()

url = "https://www.daraz.pk/catalog/?q=smart%20watch"
driver.get(url)

In [28]:
html = driver.page_source

In [29]:
soup = BeautifulSoup(html, "html.parser")

In [30]:
print("HTML length:", len(html))

HTML length: 1073524

In [31]:
links = soup.find_all("a", href=True)

product_links = []

for link in links:
    href = link.get("href")

    if "/products/" in href:
        product_links.append(href)

In [32]:
html = driver.page_source

print("HTML length:", len(html))

HTML length: 1073371

In [33]:
soup = BeautifulSoup(html, "html.parser")

print("Soup created successfully!")

Soup created successfully!

In [34]:
product_links = list(dict.fromkeys(product_links))

print("Unique product listings:", len(product_links))

Unique product listings: 40

In [35]:
product_url = product_links[0]

if product_url.startswith("//"):
    product_url = "https:" + product_url

driver.get(product_url)

print("Title:", driver.title)
print("URL:", driver.current_url)

Title: MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH | Daraz.pk
URL: https://www.daraz.pk/products/7-201-i1967558824.html

In [36]:
product_soup = BeautifulSoup(driver.page_source, "html.parser")

text = product_soup.get_text(" ", strip=True)

print(text[:5000])

MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH | Daraz.pk Product Images MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%201 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%202 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%203 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%204 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%205 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%206 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%207 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%208 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%209 MT%207%20STRAPS%20SMART-WATCH%20FULL%20SCREEN%202.01%20WATCH%20-%20Image%2010 Save More on App Download the App Sell On Daraz Help & Support Help Center Contact Customer Care Order Shipping & Delivery Payment Returns & Refunds Login Sign Up Manage My Account My Orders My Wishlist & Followed Stores My Reviews My Returns & Cancellations Logout زبان تبدیل کریں UR / Urdu EN / English SEARCH watch for boys makeup kashmiri bangles bags for girls airpods Categories Electronic Accessories TV & Home Appliances Health & Beauty Mother & Baby Electronic Devices Groceries & Pets Home & Lifestyle Women's Fashion Men's Fashion Watches, Bags & Jewellery Sports & Outdoor Automotive & Motorbike Mobile Accessories Tablet Accessories Cables & Converters Phone Cases Car Mounts Parts & Tools Screen Protectors Power Banks Phone Camera Flash Lights Selfie Sticks Car Chargers Wall Chargers Docks & Stands Camera Accessories Gimbals & Stabilizers Action Camera Accessories Lenses Tripods & Monopods Memory Cards Batteries Lighting & Studio Equipment Camera Cases, Covers and Bags Wearable Fitness & Activity Trackers Virtual Reality Network Components Access Points Computer Components Motherboards Processors Fans & Heatsinks Graphic Cards Desktop Casings Headphones & Headsets Bluetooth Headsets Wired Headsets In-Ear Headphones Over-The-Ear Headphones Headphones & Headsets Access. Wireless Earbuds Mono Headsets Printers Ink & Toners Fax Machines Storage Internal Hard Drives Storage for Mac Flash Drives OTG Drives External Hard Drives Portable Speakers Gaming Accessories Gaming Mouse Gaming Keyboards Gaming Headsets Monitors & Accessories Computer Accessories Mac Accessories Mouse Adapters & Cables PC Audio Cooling Pads/Cooling Stands Keyboards Air Conditioner Washing Machine Refrigerators & Freezers Freezers Cooling & Heating Air Cooler Air Purifier Dehumidifier Humidifier Fan Room Heater Water Heater Irons & Garment Care Irons Garment Steamer Sewing Machine Vacuums & Floor Care Electric Brooms Steam Mops Floor Polisher Vacuum Cleaner Kitchen Appliances Microwave Water Dispensers Dishwashers Cooktop & Range Oven Air & Deep Fryers Specialty Cookware Juicer & Fruit Extraction Blender, Mixer & Grinder Electric Kettle Pressure Cookers Rice Cooker Home Audio & Theater Soundbar Speakers Live Sound & Stage Equipment Home Entertainment Home Theater Systems Televisions LED Televisions Smart Televisions Projectors & Players Projectors Blu Ray & DVD Players Generator, UPS & Solar Solar Inverters Generators UPS TV Accessories Antennas TV Receivers Cables 3D Glasses TV Remote Controllers Wall Mounts & Protectors TV Adapters Men's Care Shaving & Grooming Medical Supplies Stethoscopes Surgical Masks Health Monitors & Tests Ointments and Creams Nebulizer & Aspirators Health Accessories First Aid Supplies Personal Care Adult Diapers Oral Care Eye Care Pads & Tampons Menstrual Cups Deodorants Personal Safety & Security Ear Care Hair Care Oil & Serums Hair Care Accessories Shampoo & Conditioner Hair Treatments Hair Styling Hair Coloring Beauty Tools Foot Relief Tools Slimming & Electric Massagers Hair Removal Appliances Hair Styling Appliances Skin Care Tools Makeup Bulk Deals Eyes Makeup Accessories Lips Nails Makeup Removers Makeup Palettes & Sets Face Fragrances Women Men Unisex Bath & Body Hand Care Talcum Powder Foot Care Body Moisturizers Hair Removal Body Soaps & Shower Gels Body Scrubs Bath & Body Accessories Body & Massage Oils Sexual Wellness Lubricants Condoms Skin Care Moisturizers and Cream Lip Balm & Treatment Sunscreen & Aftersun Face Mask & Packs Face Scrubs & Exfoliators Facial Cleansers Toner & Mists Serum & Essence Eye Care Clothing & Accessories Newborn Accessories New born sets & Packs Girls (Under 3 Years) Boys (Under 3 Years) New born bodysuits Maternity Care Pregnancy Pillows Maternity Accessories Breast Pumps Nursing Covers Maternity Wear Nipple Care Breast Shells Baby Gear Backpacks & Carriers Swings, Jumpers & Bouncers Harnesses & Leashes Walkers Car Seats Strollers Highchairs & Booster Seats Baby Safety Baby Monitor Kids Bag Remote Control & Vehicles Play Vehicles RC Vehicles & Batteries Drones & Accessories Die-Cast Vehicles Play Trains & Railway Sets Feeding Bottle-Feeding Bre

In [37]:
title = product_soup.find(
    string=lambda text: text and "MT 7 STRAPS SMART-WATCH" in text
)

print(title)

MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH | Daraz.pk

In [38]:
h1_tags = product_soup.find_all("h1")

print("H1 tags:", len(h1_tags))

for h1 in h1_tags:
    print(h1.get_text(" ", strip=True))

H1 tags: 1
MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH

In [39]:
product_name = product_soup.find("h1").get_text(" ", strip=True)

print("Product Name:", product_name)

Product Name: MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH

In [40]:
import time
import pandas as pd

products = []

for i, url in enumerate(product_links, start=1):

    if url.startswith("//"):
        url = "https:" + url

    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    # Product Name
    h1 = soup.find("h1")
    product_name = h1.get_text(" ", strip=True) if h1 else None

    # Price
    price = None
    price_text = soup.find(string=lambda text: text and "Rs." in text)

    if price_text:
        price = price_text.strip()

    products.append({
        "Product_Name": product_name,
        "Price": price,
        "Product_URL": url
    })

    print(f"{i}/40 - {product_name}")

print("Scraping completed!")

1/40 - MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH
2/40 - Watch Touch Screen With Bluetooth Calling/Good Battery Life
3/40 - 7 Straps Smart Fitness Tracker | Bluetooth Calling | HD Display | Full Metal Body | Heart Rate & SpO2 Monitor | Sports Activity Tracker | Music Control & Voice Assistant
4/40 - “Premium Hybrid Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
5/40 - 100% Imported High Quality watch for men , boys new design 2025
6/40 - Touch Screen| AMOLED Display | Bluetooth Calling | Heart Rate | Sports Mode
7/40 - Stainless Steel Stylish Watch For Men - New Arrival
8/40 - GT7 Pro Smartwatch 2026 Edition - Bluetooth Calling Watch with High Resolution HD Display & Full Metal Body - Professional Sports Activity Tracker, Heart Rate & SpO2 Oxygen Sensor - Music Control & Voice Assistant Fashionable Fitness Smart Band
9/40 - Zero®  Luna Smart Watch | 1.39” TFT Display, Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
10/40 - Classic Men’s Watch – Gold Plated Bezel with Steel Bracelet
11/40 - Aura Watch Arabic Original for Men - Luxury Black Watch with Marble Dial - Premium Quality Adjustable Strap Watches - Aura Watch for Boys Kids - The Art of Persuasion Style Fashion Watch - New Aura Watch White and Green - Elegant Men’s Aura Watch with Box
12/40 - Aura Watch Original Arabic - Men’s Casual Wrist Watch - Luxury Golden Aura Watch - Aura Watch for Boys and Girls - Premium Black Marble Dial Wrist Watch - Water Proof Aura Watch for Men - Best Gift Item Aura Watch with Box Pack - New Stylish Aura Watches
13/40 - Dz09 smart watch for man & women sim supported android watch calling and travelling Ratings 4
14/40 - Aura Watch for Men Stylish - Original Aura Arabic Dial Watch - Luxury Business Watch for Gents - Aura Watch Black and Blue - Fashionable Aura Watch for Girls and Boys - High Quality Aura Watches with Box - Aura Perfume Design Watch - New Arrival Watch
15/40 - Active 2 stainless steel addition with Bluetooth calling sports activity healthcare system, smart watch for man and woman
16/40 - Aura Watch for Men Original Black - Arabic Numerals Dial Watch - Luxury Aura Watches - Aura Watch for Boys Stylish - New White Dial Aura Watch - Aura Watch Arabic Original - Fashion Gents Watch - Aura Watch with Comfortable Strap - Arabic Number Watch
17/40 - wheel watch, sports wheel watch, wheel rim watch, alloy rim watch, luxury sports watch, car wheel watch, stylish watch for men, boys fashion watch, silicone strap watch, premium analog watch, trendy wrist watch Pakistan, sporty men watch, racing style wat
18/40 - New led watch for boys and girls
19/40 - Xiaomi Mi band  7 /6/ 5 Color Screen AMOLED Bluetooth 5.0 5 ATM Smart Watch Fitness Band
20/40 - Airpods with watch | 2.01" HD Screen watch | 2 in 1 Bluetooth Calling Fitness Watch with 100+ Sports Modes for Men & Women
21/40 - Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
22/40 - Watch Touch Screen With Bluetooth Calling/Good Battery Life
23/40 - Smartwach  Brand new colour black  HD Screen Water proof Heart rate, sleep monitor 100+  Water proof, 7days battery life, Heart rate, sleep monitor 100+ sports modes
24/40 - Most Trending Classic Luxury Wrist Watches for Men's Boys Watches Water Stainless Steel Waterproof Watch for Man women
25/40 - Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
26/40 - Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
27/40 - “WHEEL WATCH Premium  Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
28/40 - Sports Wheel Rim Watch ⌚🔥  Racing Rim Style Watch 🏎️💨 Stylish Men Watch 👌⌚ Premium Sports Watch 🏆⌚ Casual Fashion Watch 🎽✨ Trendy Wheel Design Watch 🛞💥 Water Resistant Watch 💧⌚ Durable Silicone Band Watch 💪
29/40 - Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
30/40 - Zero® Ignite Smart Watch | 1.83” IPS Curved Screen,  Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
31/40 - Aura Watch for Men Original - Luxury Arabic Dial Wrist Watch for Boys - Genuine Leather Strap Watch - Aura Black and White Quartz Watch for Gents - Premium Golden Watch with Box - Water Resistant Fashion Watch for Men - Stylish Aura Watches for Kids
32/40 - Zero® Elite Smart Watch | 2.04" AMOLED Display, Bluetooth 5.3, Health Monitoring, IP67 Waterproof | All-in-One Fitness and Lifestyle Smartwatch
33/40 - GT8 ULTRA WATCH.  specifically for the GT8 ultra:
​TitanEdge GT8 Ultra Chrono
34/40 - Smart Watch Camera Lens Memory Card Supported Bluetooth Calling Support 280 mAh polymer battery Micro USB cable TPU Band
35/40 - M4 Band Smart Heart Rate Fitness Band For Unisex Black
36/40 - New Smart watch Men Women Heart Rate Blood Pressure Monitoring Bluetooth Smartwatch Fitness Tracker Watch Sport For Android Ios
37/40 - Smart Watch with Ear buds
38/40 - Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
39/40 - ULTRA 7iN1 Straps 2.1 Inch HD Screen With 7 Different Straps Bluetooth Calling Smart Watch
40/40 - DZ09 Smartwatch for Men & Women | New Smart watch | Good Battery timing with SD card support upto 32 GB | Smartwatch
Scraping completed!

In [41]:
import pandas as pd

In [42]:
df = pd.DataFrame(products)

df.head()

,Product_Name,Price,Product_URL
0,MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH,"var timings = {\n start: Date.now(),\n ...",https://www.daraz.pk/products/7-201-i196755882...
1,Watch Touch Screen With Bluetooth Calling/Good...,"var timings = {\n start: Date.now(),\n ...",https://www.daraz.pk/products/watch-touch-scre...
2,7 Straps Smart Fitness Tracker | Bluetooth Cal...,"var timings = {\n start: Date.now(),\n ...",https://www.daraz.pk/products/7-straps-smart-f...
3,“Premium Hybrid Men’s Wristwatch – Rotating Ri...,"var timings = {\n start: Date.now(),\n ...",https://www.daraz.pk/products/-i938608490.html
4,"100% Imported High Quality watch for men , boy...","var timings = {\n start: Date.now(),\n ...",https://www.daraz.pk/products/100-imported-hig...

In [43]:
# Rs. wale text ke aas-paas ke elements dekho
matches = product_soup.find_all(
    string=lambda text: text and "Rs." in text
)

print("Matches:", len(matches))

for match in matches[:20]:
    print("----")
    print(repr(match))

Matches: 6
----
'\n    var timings = {\n      start: Date.now(),\n    };\n    var dataLayer = window.dataLayer || [];\n    var pdpTrackingData = "{\\"pdt_category\\":[\\"TV, Audio / Video, Gaming & Wearables\\",\\"Wearable Technology\\"],\\"pagetype\\":\\"pdp\\",\\"pdt_discount\\":\\"\\",\\"pdt_photo\\":\\"https://static-01.daraz.pk/p/508495db58b6b5a4408c15de29654392.jpg\\",\\"v_voya\\":1,\\"brand_name\\":\\"No Brand\\",\\"brand_id\\":\\"39704\\",\\"pdt_sku\\":1967558824,\\"core\\":{\\"country\\":\\"PK\\",\\"layoutType\\":\\"desktop\\",\\"language\\":\\"en\\",\\"currencyCode\\":\\"PKR\\"},\\"seller_name\\":\\"\\",\\"pdt_simplesku\\":14050340220,\\"pdt_name\\":\\"MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH\\",\\"page\\":{\\"regCategoryId\\":\\"031001000000\\",\\"xParams\\":\\"_p_typ=pdp&_p_ispdp=1&_p_item=1967558824_PK-14050340220&_p_prod=1967558824&_p_sku=14050340220&_p_slr=\\"},\\"supplier_id\\":\\"\\",\\"pdt_price\\":\\"Rs. 1,800\\",\\"extraInfo\\":{\\"traceId\\":\\"2151e60617913832780314736e2a80\\",\\"cnaByBe\\":\\"6ERNI59/xAQCASc6OL+iCU9s\\",\\"supportH5Revamp\\":\\"0\\"}}";\n    try {\n      pdpTrackingData = JSON.parse(pdpTrackingData);\n      pdpTrackingData.v_voya = false;\n      dataLayer.push(pdpTrackingData);\n      dataLayer.push({\n        gtm_enable: true, \n        v_voya: false\n      });\n    } catch (e) {\n      if (window.console) {\n        console.log(e);\n      }\n    }\n    /**\n     * 支持beacon aplus script\n     */\n    var siteNameForApluPluginLoader = "Daraz";\n\n  '
----
'Rs. 1,550'
----
'Rs. 1,800'
----
'Rs. 175'
----
'Rs. 40'
----

In [44]:
import re
import json

html = driver.page_source

match = re.search(r'var pdpTrackingData = "(.*?)";', html, re.DOTALL)

print("Found:", bool(match))

Found: True

In [45]:
import re
import json
import pandas as pd
import time

products = []

for i, url in enumerate(product_links, start=1):

    if url.startswith("//"):
        url = "https:" + url

    driver.get(url)
    time.sleep(2)

    html = driver.page_source

    # Find Daraz product tracking data
    match = re.search(
        r'var pdpTrackingData = "(.*?)";',
        html,
        re.DOTALL
    )

    if match:
        try:
            data_string = match.group(1)
            data_string = data_string.replace('\\"', '"')

            data = json.loads(data_string)

            product = {
                "Product_Name": data.get("pdt_name"),
                "Price": data.get("pdt_price"),
                "Brand": data.get("brand_name"),
                "SKU": data.get("pdt_sku"),
                "Category": data.get("pdt_category"),
                "Seller": data.get("seller_name"),
                "Product_URL": url
            }

            products.append(product)

            print(f"{i}/40 - {product['Product_Name']}")

        except Exception as e:
            print(f"{i}/40 - JSON Error:", e)

    else:
        print(f"{i}/40 - Tracking data not found")


print("\nScraping completed!")
print("Products collected:", len(products))

1/40 - MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH
2/40 - Watch Touch Screen With Bluetooth Calling/Good Battery Life
3/40 - 7 Straps Smart Fitness Tracker | Bluetooth Calling | HD Display | Full Metal Body | Heart Rate & SpO2 Monitor | Sports Activity Tracker | Music Control & Voice Assistant
4/40 - “Premium Hybrid Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
5/40 - 100% Imported High Quality watch for men , boys new design 2025
6/40 - Touch Screen| AMOLED Display | Bluetooth Calling | Heart Rate | Sports Mode
7/40 - Stainless Steel Stylish Watch For Men - New Arrival
8/40 - GT7 Pro Smartwatch 2026 Edition - Bluetooth Calling Watch with High Resolution HD Display & Full Metal Body - Professional Sports Activity Tracker, Heart Rate & SpO2 Oxygen Sensor - Music Control & Voice Assistant Fashionable Fitness Smart Band
9/40 - Zero®  Luna Smart Watch | 1.39” TFT Display, Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
10/40 - Classic Men’s Watch – Gold Plated Bezel with Steel Bracelet
11/40 - Aura Watch Arabic Original for Men - Luxury Black Watch with Marble Dial - Premium Quality Adjustable Strap Watches - Aura Watch for Boys Kids - The Art of Persuasion Style Fashion Watch - New Aura Watch White and Green - Elegant Men’s Aura Watch with Box
12/40 - Aura Watch Original Arabic - Men’s Casual Wrist Watch - Luxury Golden Aura Watch - Aura Watch for Boys and Girls - Premium Black Marble Dial Wrist Watch - Water Proof Aura Watch for Men - Best Gift Item Aura Watch with Box Pack - New Stylish Aura Watches
13/40 - Dz09 smart watch for man & women sim supported android watch calling and travelling Ratings 4
14/40 - Aura Watch for Men Stylish - Original Aura Arabic Dial Watch - Luxury Business Watch for Gents - Aura Watch Black and Blue - Fashionable Aura Watch for Girls and Boys - High Quality Aura Watches with Box - Aura Perfume Design Watch - New Arrival Watch
15/40 - Active 2 stainless steel addition with Bluetooth calling sports activity healthcare system, smart watch for man and woman
16/40 - Aura Watch for Men Original Black - Arabic Numerals Dial Watch - Luxury Aura Watches - Aura Watch for Boys Stylish - New White Dial Aura Watch - Aura Watch Arabic Original - Fashion Gents Watch - Aura Watch with Comfortable Strap - Arabic Number Watch
17/40 - wheel watch, sports wheel watch, wheel rim watch, alloy rim watch, luxury sports watch, car wheel watch, stylish watch for men, boys fashion watch, silicone strap watch, premium analog watch, trendy wrist watch Pakistan, sporty men watch, racing style wat
18/40 - New led watch for boys and girls
19/40 - Xiaomi Mi band  7 /6/ 5 Color Screen AMOLED Bluetooth 5.0 5 ATM Smart Watch Fitness Band
20/40 - JSON Error: Expecting ',' delimiter: line 1 column 382 (char 381)
21/40 - Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
22/40 - Watch Touch Screen With Bluetooth Calling/Good Battery Life
23/40 - Smartwach  Brand new colour black  HD Screen Water proof Heart rate, sleep monitor 100+  Water proof, 7days battery life, Heart rate, sleep monitor 100+ sports modes
24/40 - Most Trending Classic Luxury Wrist Watches for Men's Boys Watches Water Stainless Steel Waterproof Watch for Man women
25/40 - Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
26/40 - Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
27/40 - “WHEEL WATCH Premium  Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
28/40 - Sports Wheel Rim Watch ⌚🔥  Racing Rim Style Watch 🏎️💨 Stylish Men Watch 👌⌚ Premium Sports Watch 🏆⌚ Casual Fashion Watch 🎽✨ Trendy Wheel Design Watch 🛞💥 Water Resistant Watch 💧⌚ Durable Silicone Band Watch 💪
29/40 - Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
30/40 - Zero® Ignite Smart Watch | 1.83” IPS Curved Screen,  Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
31/40 - Aura Watch for Men Original - Luxury Arabic Dial Wrist Watch for Boys - Genuine Leather Strap Watch - Aura Black and White Quartz Watch for Gents - Premium Golden Watch with Box - Water Resistant Fashion Watch for Men - Stylish Aura Watches for Kids
32/40 - JSON Error: Expecting ',' delimiter: line 1 column 454 (char 453)
33/40 - GT8 ULTRA WATCH.  specifically for the GT8 ultra:\n​TitanEdge GT8 Ultra Chrono
34/40 - Smart Watch Camera Lens Memory Card Supported Bluetooth Calling Support 280 mAh polymer battery Micro USB cable TPU Band
35/40 - M4 Band Smart Heart Rate Fitness Band For Unisex Black
36/40 - New Smart watch Men Women Heart Rate Blood Pressure Monitoring Bluetooth Smartwatch Fitness Tracker Watch Sport For Android Ios
37/40 - Smart Watch with Ear buds
38/40 - Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
39/40 - ULTRA 7iN1 Straps 2.1 Inch HD Screen With 7 Different Straps Bluetooth Calling Smart Watch
40/40 - DZ09 Smartwatch for Men & Women | New Smart watch | Good Battery timing with SD card support upto 32 GB | Smartwatch

Scraping completed!
Products collected: 38

In [46]:
df = pd.DataFrame(products)

df.head()

,Product_Name,Price,Brand,SKU,Category,Seller,Product_URL
0,MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH,"Rs. 1,800",No Brand,1967558824,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/7-201-i196755882...
1,Watch Touch Screen With Bluetooth Calling/Good...,"Rs. 3,000",No Brand,1967736868,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/watch-touch-scre...
2,7 Straps Smart Fitness Tracker | Bluetooth Cal...,"Rs. 2,620",.No Brand.,1968212662,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/7-straps-smart-f...
3,“Premium Hybrid Men’s Wristwatch – Rotating Ri...,"Rs. 6,000",No Brand,938608490,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i938608490.html
4,"100% Imported High Quality watch for men , boy...","Rs. 2,699",Hasnain Mart,489062580,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/100-imported-hig...

In [47]:
print("Total collected:", len(df))

Total collected: 38

In [48]:
df

,Product_Name,Price,Brand,SKU,Category,Seller,Product_URL
0,MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH,"Rs. 1,800",No Brand,1967558824,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/7-201-i196755882...
1,Watch Touch Screen With Bluetooth Calling/Good...,"Rs. 3,000",No Brand,1967736868,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/watch-touch-scre...
2,7 Straps Smart Fitness Tracker | Bluetooth Cal...,"Rs. 2,620",.No Brand.,1968212662,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/7-straps-smart-f...
3,“Premium Hybrid Men’s Wristwatch – Rotating Ri...,"Rs. 6,000",No Brand,938608490,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i938608490.html
4,"100% Imported High Quality watch for men , boy...","Rs. 2,699",Hasnain Mart,489062580,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/100-imported-hig...
5,Touch Screen| AMOLED Display | Bluetooth Calli...,Rs. 50,No Brand,363479683,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/amoled-i36347968...
6,Stainless Steel Stylish Watch For Men - New Ar...,"Rs. 1,499",No Brand,17436892,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i17436892.html
7,GT7 Pro Smartwatch 2026 Edition - Bluetooth Ca...,"Rs. 4,000",No Brand,1955707460,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/7-2026-2-i195570...
8,"Zero® Luna Smart Watch | 1.39” TFT Display, C...","Rs. 21,499",Zero Lifestyle,434227378,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/zero-luna-smart-...
9,Classic Men’s Watch – Gold Plated Bezel with S...,"Rs. 1,999",No Brand,924544089,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i924544089.html
10,Aura Watch Arabic Original for Men - Luxury Bl...,"Rs. 2,000",No Brand,1948623357,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1948623357.html
11,Aura Watch Original Arabic - Men’s Casual Wris...,"Rs. 2,000",No Brand,1948647217,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1948647217.html
12,Dz09 smart watch for man & women sim supported...,"Rs. 4,599",No Brand,659908187,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/dz09-4dz09-smart...
13,Aura Watch for Men Stylish - Original Aura Ara...,"Rs. 1,888",No Brand,1948623358,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1948623358.html
14,Active 2 stainless steel addition with Bluetoo...,"Rs. 3,999",No Brand,940137491,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/2-i940137491.html
15,Aura Watch for Men Original Black - Arabic Num...,"Rs. 2,000",No Brand,1948804327,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1948804327.html
16,"wheel watch, sports wheel watch, wheel rim wat...","Rs. 4,999",No Brand,1957796823,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1957796823.html
17,New led watch for boys and girls,Rs. 375,No Brand,440086447,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/new-led-watch-fo...
18,Xiaomi Mi band 7 /6/ 5 Color Screen AMOLED Bl...,"Rs. 6,749",.No Brand.,1967336542,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/xiaomi-mi-band-7...
19,Black Arabic Aura Watch For Men – Elegant Desi...,"Rs. 2,500",No Brand,916257605,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i916257605.html
20,Watch Touch Screen With Bluetooth Calling/Good...,"Rs. 3,000",No Brand,1967291804,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/watch-touch-scre...
21,Smartwach Brand new colour black HD Screen W...,"Rs. 4,500",No Brand,481583856,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/100-7-100-i48158...
22,Most Trending Classic Luxury Wrist Watches for...,Rs. 999,No Brand,316687937,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i316687937.html
23,Watch for Boys Digital Watch Waterproof Stainl...,"Rs. 1,499",No Brand,1953749088,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/kco-a159wa-n1df-...
24,Black Arabic Aura Watch For Men – Elegant Desi...,"Rs. 1,499",No Brand,924743769,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i924743769.html
25,“WHEEL WATCH Premium Men’s Wristwatch – Rotat...,"Rs. 8,000",No Brand,941444342,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i941444342.html
26,Sports Wheel Rim Watch ⌚🔥 Racing Rim Style Wa...,"Rs. 6,000",NO BRAND,948425856,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i948425856.html
27,Watch for Boys Digital Watch Waterproof Stainl...,"Rs. 1,499",No Brand,1954042336,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/kco-a159wa-n1df-...
28,Zero® Ignite Smart Watch | 1.83” IPS Curved Sc...,"Rs. 24,999",Zero Lifestyle,434227185,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/zero-ignite-smar...
29,Aura Watch for Men Original - Luxury Arabic Di...,"Rs. 1,499",No Brand,1948812342,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1948812342.html
30,GT8 ULTRA WATCH. specifically for the GT8 ult...,"Rs. 4,500",No Brand,1968011710,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/8-8-8-i196801171...
31,Smart Watch Camera Lens Memory Card Supported ...,"Rs. 4,500",No Brand,477707602,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/280-mah-usb-tpu-...
32,M4 Band Smart Heart Rate Fitness Band For Unis...,"Rs. 4,999",,116628392,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/m4-i116628392.html
33,New Smart watch Men Women Heart Rate Blood Pre...,"Rs. 3,860",No Brand,1958554294,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1958554294.html
34,Smart Watch with Ear buds,"Rs. 3,500",No Brand,666984206,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i666984206.html
35,Black Arabic Aura Watch For Men – Elegant Desi...,"Rs. 1,499",No Brand,1948814273,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/-i1948814273.html
36,ULTRA 7iN1 Straps 2.1 Inch HD Screen With 7 Di...,"Rs. 3,699",No Brand,607435532,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/7-1-1-hd-7-i6074...
37,DZ09 Smartwatch for Men & Women | New Smart wa...,"Rs. 5,000",No Brand,465346711,"[TV, Audio / Video, Gaming & Wearables, Wearab...",,https://www.daraz.pk/products/dz09-sd-32-gb-i4...

In [49]:
print("Products list:", len(products))
print("DataFrame rows:", len(df))

Products list: 38
DataFrame rows: 38

In [50]:
for i, product in enumerate(products):
    print(i, product.get("Product_Name"))

0 MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH
1 Watch Touch Screen With Bluetooth Calling/Good Battery Life
2 7 Straps Smart Fitness Tracker | Bluetooth Calling | HD Display | Full Metal Body | Heart Rate & SpO2 Monitor | Sports Activity Tracker | Music Control & Voice Assistant
3 “Premium Hybrid Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
4 100% Imported High Quality watch for men , boys new design 2025
5 Touch Screen| AMOLED Display | Bluetooth Calling | Heart Rate | Sports Mode
6 Stainless Steel Stylish Watch For Men - New Arrival
7 GT7 Pro Smartwatch 2026 Edition - Bluetooth Calling Watch with High Resolution HD Display & Full Metal Body - Professional Sports Activity Tracker, Heart Rate & SpO2 Oxygen Sensor - Music Control & Voice Assistant Fashionable Fitness Smart Band
8 Zero®  Luna Smart Watch | 1.39” TFT Display, Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
9 Classic Men’s Watch – Gold Plated Bezel with Steel Bracelet
10 Aura Watch Arabic Original for Men - Luxury Black Watch with Marble Dial - Premium Quality Adjustable Strap Watches - Aura Watch for Boys Kids - The Art of Persuasion Style Fashion Watch - New Aura Watch White and Green - Elegant Men’s Aura Watch with Box
11 Aura Watch Original Arabic - Men’s Casual Wrist Watch - Luxury Golden Aura Watch - Aura Watch for Boys and Girls - Premium Black Marble Dial Wrist Watch - Water Proof Aura Watch for Men - Best Gift Item Aura Watch with Box Pack - New Stylish Aura Watches
12 Dz09 smart watch for man & women sim supported android watch calling and travelling Ratings 4
13 Aura Watch for Men Stylish - Original Aura Arabic Dial Watch - Luxury Business Watch for Gents - Aura Watch Black and Blue - Fashionable Aura Watch for Girls and Boys - High Quality Aura Watches with Box - Aura Perfume Design Watch - New Arrival Watch
14 Active 2 stainless steel addition with Bluetooth calling sports activity healthcare system, smart watch for man and woman
15 Aura Watch for Men Original Black - Arabic Numerals Dial Watch - Luxury Aura Watches - Aura Watch for Boys Stylish - New White Dial Aura Watch - Aura Watch Arabic Original - Fashion Gents Watch - Aura Watch with Comfortable Strap - Arabic Number Watch
16 wheel watch, sports wheel watch, wheel rim watch, alloy rim watch, luxury sports watch, car wheel watch, stylish watch for men, boys fashion watch, silicone strap watch, premium analog watch, trendy wrist watch Pakistan, sporty men watch, racing style wat
17 New led watch for boys and girls
18 Xiaomi Mi band  7 /6/ 5 Color Screen AMOLED Bluetooth 5.0 5 ATM Smart Watch Fitness Band
19 Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
20 Watch Touch Screen With Bluetooth Calling/Good Battery Life
21 Smartwach  Brand new colour black  HD Screen Water proof Heart rate, sleep monitor 100+  Water proof, 7days battery life, Heart rate, sleep monitor 100+ sports modes
22 Most Trending Classic Luxury Wrist Watches for Men's Boys Watches Water Stainless Steel Waterproof Watch for Man women
23 Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
24 Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
25 “WHEEL WATCH Premium  Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
26 Sports Wheel Rim Watch ⌚🔥  Racing Rim Style Watch 🏎️💨 Stylish Men Watch 👌⌚ Premium Sports Watch 🏆⌚ Casual Fashion Watch 🎽✨ Trendy Wheel Design Watch 🛞💥 Water Resistant Watch 💧⌚ Durable Silicone Band Watch 💪
27 Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
28 Zero® Ignite Smart Watch | 1.83” IPS Curved Screen,  Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
29 Aura Watch for Men Original - Luxury Arabic Dial Wrist Watch for Boys - Genuine Leather Strap Watch - Aura Black and White Quartz Watch for Gents - Premium Golden Watch with Box - Water Resistant Fashion Watch for Men - Stylish Aura Watches for Kids
30 GT8 ULTRA WATCH.  specifically for the GT8 ultra:\n​TitanEdge GT8 Ultra Chrono
31 Smart Watch Camera Lens Memory Card Supported Bluetooth Calling Support 280 mAh polymer battery Micro USB cable TPU Band
32 M4 Band Smart Heart Rate Fitness Band For Unisex Black
33 New Smart watch Men Women Heart Rate Blood Pressure Monitoring Bluetooth Smartwatch Fitness Tracker Watch Sport For Android Ios
34 Smart Watch with Ear buds
35 Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
36 ULTRA 7iN1 Straps 2.1 Inch HD Screen With 7 Different Straps Bluetooth Calling Smart Watch
37 DZ09 Smartwatch for Men & Women | New Smart watch | Good Battery timing with SD card support upto 32 GB | Smartwatch

In [51]:
for i, name in enumerate(df["Product_Name"], start=1):
    print(i, "→", name)

1 → MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH
2 → Watch Touch Screen With Bluetooth Calling/Good Battery Life
3 → 7 Straps Smart Fitness Tracker | Bluetooth Calling | HD Display | Full Metal Body | Heart Rate & SpO2 Monitor | Sports Activity Tracker | Music Control & Voice Assistant
4 → “Premium Hybrid Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
5 → 100% Imported High Quality watch for men , boys new design 2025
6 → Touch Screen| AMOLED Display | Bluetooth Calling | Heart Rate | Sports Mode
7 → Stainless Steel Stylish Watch For Men - New Arrival
8 → GT7 Pro Smartwatch 2026 Edition - Bluetooth Calling Watch with High Resolution HD Display & Full Metal Body - Professional Sports Activity Tracker, Heart Rate & SpO2 Oxygen Sensor - Music Control & Voice Assistant Fashionable Fitness Smart Band
9 → Zero®  Luna Smart Watch | 1.39” TFT Display, Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
10 → Classic Men’s Watch – Gold Plated Bezel with Steel Bracelet
11 → Aura Watch Arabic Original for Men - Luxury Black Watch with Marble Dial - Premium Quality Adjustable Strap Watches - Aura Watch for Boys Kids - The Art of Persuasion Style Fashion Watch - New Aura Watch White and Green - Elegant Men’s Aura Watch with Box
12 → Aura Watch Original Arabic - Men’s Casual Wrist Watch - Luxury Golden Aura Watch - Aura Watch for Boys and Girls - Premium Black Marble Dial Wrist Watch - Water Proof Aura Watch for Men - Best Gift Item Aura Watch with Box Pack - New Stylish Aura Watches
13 → Dz09 smart watch for man & women sim supported android watch calling and travelling Ratings 4
14 → Aura Watch for Men Stylish - Original Aura Arabic Dial Watch - Luxury Business Watch for Gents - Aura Watch Black and Blue - Fashionable Aura Watch for Girls and Boys - High Quality Aura Watches with Box - Aura Perfume Design Watch - New Arrival Watch
15 → Active 2 stainless steel addition with Bluetooth calling sports activity healthcare system, smart watch for man and woman
16 → Aura Watch for Men Original Black - Arabic Numerals Dial Watch - Luxury Aura Watches - Aura Watch for Boys Stylish - New White Dial Aura Watch - Aura Watch Arabic Original - Fashion Gents Watch - Aura Watch with Comfortable Strap - Arabic Number Watch
17 → wheel watch, sports wheel watch, wheel rim watch, alloy rim watch, luxury sports watch, car wheel watch, stylish watch for men, boys fashion watch, silicone strap watch, premium analog watch, trendy wrist watch Pakistan, sporty men watch, racing style wat
18 → New led watch for boys and girls
19 → Xiaomi Mi band  7 /6/ 5 Color Screen AMOLED Bluetooth 5.0 5 ATM Smart Watch Fitness Band
20 → Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
21 → Watch Touch Screen With Bluetooth Calling/Good Battery Life
22 → Smartwach  Brand new colour black  HD Screen Water proof Heart rate, sleep monitor 100+  Water proof, 7days battery life, Heart rate, sleep monitor 100+ sports modes
23 → Most Trending Classic Luxury Wrist Watches for Men's Boys Watches Water Stainless Steel Waterproof Watch for Man women
24 → Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
25 → Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
26 → “WHEEL WATCH Premium  Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch
27 → Sports Wheel Rim Watch ⌚🔥  Racing Rim Style Watch 🏎️💨 Stylish Men Watch 👌⌚ Premium Sports Watch 🏆⌚ Casual Fashion Watch 🎽✨ Trendy Wheel Design Watch 🛞💥 Water Resistant Watch 💧⌚ Durable Silicone Band Watch 💪
28 → Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch
29 → Zero® Ignite Smart Watch | 1.83” IPS Curved Screen,  Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android
30 → Aura Watch for Men Original - Luxury Arabic Dial Wrist Watch for Boys - Genuine Leather Strap Watch - Aura Black and White Quartz Watch for Gents - Premium Golden Watch with Box - Water Resistant Fashion Watch for Men - Stylish Aura Watches for Kids
31 → GT8 ULTRA WATCH.  specifically for the GT8 ultra:\n​TitanEdge GT8 Ultra Chrono
32 → Smart Watch Camera Lens Memory Card Supported Bluetooth Calling Support 280 mAh polymer battery Micro USB cable TPU Band
33 → M4 Band Smart Heart Rate Fitness Band For Unisex Black
34 → New Smart watch Men Women Heart Rate Blood Pressure Monitoring Bluetooth Smartwatch Fitness Tracker Watch Sport For Android Ios
35 → Smart Watch with Ear buds
36 → Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
37 → ULTRA 7iN1 Straps 2.1 Inch HD Screen With 7 Different Straps Bluetooth Calling Smart Watch
38 → DZ09 Smartwatch for Men & Women | New Smart watch | Good Battery timing with SD card support upto 32 GB | Smartwatch

In [52]:
duplicates = df[df.duplicated(subset="Product_Name", keep=False)]

print("Duplicate rows:", len(duplicates))
print()

for name in duplicates["Product_Name"].unique():
    print("→", name)

Duplicate rows: 7

→ Watch Touch Screen With Bluetooth Calling/Good Battery Life
→ Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅
→ Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch

In [53]:
duplicate_data = df[df.duplicated("Product_Name", keep=False)]

duplicate_data[
    ["Product_Name", "SKU", "Price", "Brand", "Product_URL"]
]

,Product_Name,SKU,Price,Brand,Product_URL
1,Watch Touch Screen With Bluetooth Calling/Good...,1967736868,"Rs. 3,000",No Brand,https://www.daraz.pk/products/watch-touch-scre...
19,Black Arabic Aura Watch For Men – Elegant Desi...,916257605,"Rs. 2,500",No Brand,https://www.daraz.pk/products/-i916257605.html
20,Watch Touch Screen With Bluetooth Calling/Good...,1967291804,"Rs. 3,000",No Brand,https://www.daraz.pk/products/watch-touch-scre...
23,Watch for Boys Digital Watch Waterproof Stainl...,1953749088,"Rs. 1,499",No Brand,https://www.daraz.pk/products/kco-a159wa-n1df-...
24,Black Arabic Aura Watch For Men – Elegant Desi...,924743769,"Rs. 1,499",No Brand,https://www.daraz.pk/products/-i924743769.html
27,Watch for Boys Digital Watch Waterproof Stainl...,1954042336,"Rs. 1,499",No Brand,https://www.daraz.pk/products/kco-a159wa-n1df-...
35,Black Arabic Aura Watch For Men – Elegant Desi...,1948814273,"Rs. 1,499",No Brand,https://www.daraz.pk/products/-i1948814273.html

In [54]:
df.to_csv("smart_watch_products.csv", index=False)

print("Total products:", len(df))
print("CSV saved successfully!")

Total products: 38
CSV saved successfully!

In [55]:
print(products)

[{'Product_Name': 'MT 7 STRAPS SMART-WATCH FULL SCREEN 2.01 WATCH', 'Price': 'Rs. 1,800', 'Brand': 'No Brand', 'SKU': 1967558824, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/7-201-i1967558824.html'}, {'Product_Name': 'Watch Touch Screen With Bluetooth Calling/Good Battery Life', 'Price': 'Rs. 3,000', 'Brand': 'No Brand', 'SKU': 1967736868, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/watch-touch-screen-with-bluetooth-callinggood-battery-life-i1967736868.html'}, {'Product_Name': '7 Straps Smart Fitness Tracker | Bluetooth Calling | HD Display | Full Metal Body | Heart Rate & SpO2 Monitor | Sports Activity Tracker | Music Control & Voice Assistant', 'Price': 'Rs. 2,620', 'Brand': '.No Brand.', 'SKU': 1968212662, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/7-straps-smart-fitness-tracker-bluetooth-calling-hd-display-full-metal-body-heart-rate-spo2-monitor-sports-activity-tracker-music-control-voice-assistant-i1968212662.html'}, {'Product_Name': '“Premium Hybrid Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch', 'Price': 'Rs. 6,000', 'Brand': 'No Brand', 'SKU': 938608490, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i938608490.html'}, {'Product_Name': '100% Imported High Quality watch for men , boys new design 2025', 'Price': 'Rs. 2,699', 'Brand': 'Hasnain Mart', 'SKU': 489062580, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/100-imported-high-quality-watch-for-men-boys-new-design-2025-i489062580.html'}, {'Product_Name': 'Touch Screen| AMOLED Display | Bluetooth Calling | Heart Rate | Sports Mode', 'Price': 'Rs. 50', 'Brand': 'No Brand', 'SKU': 363479683, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/amoled-i363479683.html'}, {'Product_Name': 'Stainless Steel Stylish Watch For Men - New Arrival', 'Price': 'Rs. 1,499', 'Brand': 'No Brand', 'SKU': 17436892, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i17436892.html'}, {'Product_Name': 'GT7 Pro Smartwatch 2026 Edition - Bluetooth Calling Watch with High Resolution HD Display & Full Metal Body - Professional Sports Activity Tracker, Heart Rate & SpO2 Oxygen Sensor - Music Control & Voice Assistant Fashionable Fitness Smart Band', 'Price': 'Rs. 4,000', 'Brand': 'No Brand', 'SKU': 1955707460, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/7-2026-2-i1955707460.html'}, {'Product_Name': 'Zero®  Luna Smart Watch | 1.39” TFT Display, Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android', 'Price': 'Rs. 21,499', 'Brand': 'Zero Lifestyle', 'SKU': 434227378, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/zero-luna-smart-watch-139-tft-display-calling-100-watch-faces-ip67-waterproof-spo2-heart-rate-monitor-best-price-smartwatch-for-men-women-ios-android-i434227378.html'}, {'Product_Name': 'Classic Men’s Watch – Gold Plated Bezel with Steel Bracelet', 'Price': 'Rs. 1,999', 'Brand': 'No Brand', 'SKU': 924544089, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i924544089.html'}, {'Product_Name': 'Aura Watch Arabic Original for Men - Luxury Black Watch with Marble Dial - Premium Quality Adjustable Strap Watches - Aura Watch for Boys Kids - The Art of Persuasion Style Fashion Watch - New Aura Watch White and Green - Elegant Men’s Aura Watch with Box', 'Price': 'Rs. 2,000', 'Brand': 'No Brand', 'SKU': 1948623357, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1948623357.html'}, {'Product_Name': 'Aura Watch Original Arabic - Men’s Casual Wrist Watch - Luxury Golden Aura Watch - Aura Watch for Boys and Girls - Premium Black Marble Dial Wrist Watch - Water Proof Aura Watch for Men - Best Gift Item Aura Watch with Box Pack - New Stylish Aura Watches', 'Price': 'Rs. 2,000', 'Brand': 'No Brand', 'SKU': 1948647217, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1948647217.html'}, {'Product_Name': 'Dz09 smart watch for man & women sim supported android watch calling and travelling Ratings 4', 'Price': 'Rs. 4,599', 'Brand': 'No Brand', 'SKU': 659908187, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/dz09-4dz09-smart-watch-for-man-women-sim-supported-android-watch-calling-and-travelling-ratings-4-i659908187.html'}, {'Product_Name': 'Aura Watch for Men Stylish - Original Aura Arabic Dial Watch - Luxury Business Watch for Gents - Aura Watch Black and Blue - Fashionable Aura Watch for Girls and Boys - High Quality Aura Watches with Box - Aura Perfume Design Watch - New Arrival Watch', 'Price': 'Rs. 1,888', 'Brand': 'No Brand', 'SKU': 1948623358, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1948623358.html'}, {'Product_Name': 'Active 2 stainless steel addition with Bluetooth calling sports activity healthcare system, smart watch for man and woman', 'Price': 'Rs. 3,999', 'Brand': 'No Brand', 'SKU': 940137491, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/2-i940137491.html'}, {'Product_Name': 'Aura Watch for Men Original Black - Arabic Numerals Dial Watch - Luxury Aura Watches - Aura Watch for Boys Stylish - New White Dial Aura Watch - Aura Watch Arabic Original - Fashion Gents Watch - Aura Watch with Comfortable Strap - Arabic Number Watch', 'Price': 'Rs. 2,000', 'Brand': 'No Brand', 'SKU': 1948804327, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1948804327.html'}, {'Product_Name': 'wheel watch, sports wheel watch, wheel rim watch, alloy rim watch, luxury sports watch, car wheel watch, stylish watch for men, boys fashion watch, silicone strap watch, premium analog watch, trendy wrist watch Pakistan, sporty men watch, racing style wat', 'Price': 'Rs. 4,999', 'Brand': 'No Brand', 'SKU': 1957796823, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1957796823.html'}, {'Product_Name': 'New led watch for boys and girls', 'Price': 'Rs. 375', 'Brand': 'No Brand', 'SKU': 440086447, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/new-led-watch-for-boys-and-girls-i440086447.html'}, {'Product_Name': 'Xiaomi Mi band  7 /6/ 5 Color Screen AMOLED Bluetooth 5.0 5 ATM Smart Watch Fitness Band', 'Price': 'Rs. 6,749', 'Brand': '.No Brand.', 'SKU': 1967336542, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/xiaomi-mi-band-7-6-5-color-screen-amoled-bluetooth-50-5-atm-smart-watch-fitness-band-i1967336542.html'}, {'Product_Name': 'Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅', 'Price': 'Rs. 2,500', 'Brand': 'No Brand', 'SKU': 916257605, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i916257605.html'}, {'Product_Name': 'Watch Touch Screen With Bluetooth Calling/Good Battery Life', 'Price': 'Rs. 3,000', 'Brand': 'No Brand', 'SKU': 1967291804, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/watch-touch-screen-with-bluetooth-callinggood-battery-life-i1967291804.html'}, {'Product_Name': 'Smartwach  Brand new colour black  HD Screen Water proof Heart rate, sleep monitor 100+  Water proof, 7days battery life, Heart rate, sleep monitor 100+ sports modes', 'Price': 'Rs. 4,500', 'Brand': 'No Brand', 'SKU': 481583856, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/100-7-100-i481583856.html'}, {'Product_Name': "Most Trending Classic Luxury Wrist Watches for Men's Boys Watches Water Stainless Steel Waterproof Watch for Man women", 'Price': 'Rs. 999', 'Brand': 'No Brand', 'SKU': 316687937, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i316687937.html'}, {'Product_Name': 'Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch', 'Price': 'Rs. 1,499', 'Brand': 'No Brand', 'SKU': 1953749088, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/kco-a159wa-n1df-i1953749088.html'}, {'Product_Name': 'Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅', 'Price': 'Rs. 1,499', 'Brand': 'No Brand', 'SKU': 924743769, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i924743769.html'}, {'Product_Name': '“WHEEL WATCH Premium  Men’s Wristwatch – Rotating Rim Dial, Multi-Function Modern Design, Waterproof Metal Strap”Look Like Smart Watch', 'Price': 'Rs. 8,000', 'Brand': 'No Brand', 'SKU': 941444342, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i941444342.html'}, {'Product_Name': 'Sports Wheel Rim Watch ⌚🔥  Racing Rim Style Watch 🏎️💨 Stylish Men Watch 👌⌚ Premium Sports Watch 🏆⌚ Casual Fashion Watch 🎽✨ Trendy Wheel Design Watch 🛞💥 Water Resistant Watch 💧⌚ Durable Silicone Band Watch 💪', 'Price': 'Rs. 6,000', 'Brand': 'NO BRAND', 'SKU': 948425856, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i948425856.html'}, {'Product_Name': 'Watch for Boys Digital Watch Waterproof Stainless Steel Analock Watch for Men Watch Mens & Womens Watch KCO A159WA-N1DF Classic Black Chrono Premium Quality Casual Wrist Watch Numerals Butterfly Clasp Stealness Steel Chain Imported Gift Watch', 'Price': 'Rs. 1,499', 'Brand': 'No Brand', 'SKU': 1954042336, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/kco-a159wa-n1df-i1954042336.html'}, {'Product_Name': 'Zero® Ignite Smart Watch | 1.83” IPS Curved Screen,  Calling, 100+ Watch Faces | IP67 Waterproof, SpO2 & Heart Rate Monitor | Best Price Smartwatch for Men & Women, IOS & Android', 'Price': 'Rs. 24,999', 'Brand': 'Zero Lifestyle', 'SKU': 434227185, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/zero-ignite-smart-watch-183-ips-curved-screen-calling-100-watch-faces-ip67-waterproof-spo2-heart-rate-monitor-best-price-smartwatch-for-men-women-ios-android-i434227185.html'}, {'Product_Name': 'Aura Watch for Men Original - Luxury Arabic Dial Wrist Watch for Boys - Genuine Leather Strap Watch - Aura Black and White Quartz Watch for Gents - Premium Golden Watch with Box - Water Resistant Fashion Watch for Men - Stylish Aura Watches for Kids', 'Price': 'Rs. 1,499', 'Brand': 'No Brand', 'SKU': 1948812342, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1948812342.html'}, {'Product_Name': 'GT8 ULTRA WATCH.  specifically for the GT8 ultra:\\n\u200bTitanEdge GT8 Ultra Chrono', 'Price': 'Rs. 4,500', 'Brand': 'No Brand', 'SKU': 1968011710, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/8-8-8-i1968011710.html'}, {'Product_Name': 'Smart Watch Camera Lens Memory Card Supported Bluetooth Calling Support 280 mAh polymer battery Micro USB cable TPU Band', 'Price': 'Rs. 4,500', 'Brand': 'No Brand', 'SKU': 477707602, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/280-mah-usb-tpu-i477707602.html'}, {'Product_Name': 'M4 Band Smart Heart Rate Fitness Band For Unisex Black', 'Price': 'Rs. 4,999', 'Brand': '', 'SKU': 116628392, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/m4-i116628392.html'}, {'Product_Name': 'New Smart watch Men Women Heart Rate Blood Pressure Monitoring Bluetooth Smartwatch Fitness Tracker Watch Sport For Android Ios', 'Price': 'Rs. 3,860', 'Brand': 'No Brand', 'SKU': 1958554294, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1958554294.html'}, {'Product_Name': 'Smart Watch with Ear buds', 'Price': 'Rs. 3,500', 'Brand': 'No Brand', 'SKU': 666984206, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i666984206.html'}, {'Product_Name': 'Black Arabic Aura Watch For Men – Elegant Design, Arabic Numerals, Premium Quartz Movement ✅', 'Price': 'Rs. 1,499', 'Brand': 'No Brand', 'SKU': 1948814273, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/-i1948814273.html'}, {'Product_Name': 'ULTRA 7iN1 Straps 2.1 Inch HD Screen With 7 Different Straps Bluetooth Calling Smart Watch', 'Price': 'Rs. 3,699', 'Brand': 'No Brand', 'SKU': 607435532, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/7-1-1-hd-7-i607435532.html'}, {'Product_Name': 'DZ09 Smartwatch for Men & Women | New Smart watch | Good Battery timing with SD card support upto 32 GB | Smartwatch', 'Price': 'Rs. 5,000', 'Brand': 'No Brand', 'SKU': 465346711, 'Category': ['TV, Audio / Video, Gaming & Wearables', 'Wearable Technology'], 'Seller': '', 'Product_URL': 'https://www.daraz.pk/products/dz09-sd-32-gb-i465346711.html'}]

In [56]:
import pandas as pd

df = pd.DataFrame(products)

print("Total products:", len(df))
print("Total columns:", len(df.columns))

df.to_csv("smart_watch_products.csv", index=False)

print("CSV saved successfully!")

Total products: 38
Total columns: 7
CSV saved successfully!